# Generated by Django 5.0 on 2024-02-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_is_complated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_complated',
        ),
    ]
