# Generated by Django 5.0.1 on 2024-02-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCheap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('new_price', models.SmallIntegerField(verbose_name='Цена продукта со скидкой')),
                ('old_price', models.SmallIntegerField(verbose_name='Цена продукта без скидки')),
            ],
            options={
                'verbose_name': 'Продукт по скидке',
                'verbose_name_plural': 'Продукты по скидкам',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта')),
                ('photo', models.ImageField(upload_to='shop_products/', verbose_name='Фото продукта')),
                ('new_price', models.SmallIntegerField(verbose_name='Цена продукта со скидкой')),
                ('old_price', models.SmallIntegerField(verbose_name='Цена продукта без скидки')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
