# Generated by Django 5.0.1 on 2024-02-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopcategory_shopcheap_category_shopproduct_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopCheap',
            new_name='ShopDish',
        ),
        migrations.AlterModelOptions(
            name='shopdish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='photo',
        ),
    ]
