# Generated by Django 5.0.1 on 2024-02-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_name_shopproduct_title_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='image',
            field=models.ImageField(default=1, upload_to='products/', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='sku',
            field=models.CharField(default=1, max_length=255, verbose_name='SKU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='tags',
            field=models.CharField(default=1, max_length=255, verbose_name='Тэги'),
            preserve_default=False,
        ),
    ]
