# Generated by Django 5.0 on 2024-02-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Баланс'),
        ),
    ]
