# Generated by Django 5.0.1 on 2024-02-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок сайта')),
                ('logo', models.ImageField(upload_to='settings/logo/', verbose_name='Логотип сайта')),
                ('banner_1', models.ImageField(upload_to='settings/banner/', verbose_name='Первый банер на главой странице')),
                ('title_1', models.CharField(max_length=255, verbose_name='Первый заголовок на главной странице')),
                ('description_1', models.TextField(verbose_name='Первый текст на главной странице')),
                ('banner_2', models.ImageField(upload_to='settings/banner2/', verbose_name='Второй банер на главой странице')),
                ('title_2', models.CharField(max_length=255, verbose_name='Второй заголовок на главной странице')),
                ('description_2', models.TextField(verbose_name='Второй текст на главной странице')),
                ('title_3', models.CharField(max_length=255, verbose_name='Третий заголовок на главной странице')),
                ('description_3', models.TextField(verbose_name='Третий текст на главной странице')),
                ('quality_1', models.CharField(max_length=50, verbose_name='Первое качество')),
                ('quality_desc_1', models.CharField(max_length=100, verbose_name='Описание первого качества')),
                ('quality_2', models.CharField(max_length=50, verbose_name='Второе качество')),
                ('quality_desc_2', models.CharField(max_length=100, verbose_name='Описание второго качества')),
                ('quality_3', models.CharField(max_length=50, verbose_name='Третье качество')),
                ('quality_desc_3', models.CharField(max_length=100, verbose_name='Описание третьего качества')),
                ('quality_4', models.CharField(max_length=50, verbose_name='Четвертое качество')),
                ('quality_desc_4', models.CharField(max_length=100, verbose_name='Описание четвертого качества')),
                ('_copyright', models.CharField(max_length=255, verbose_name='Текст copyright')),
                ('loader', models.ImageField(upload_to='settings/loader/', verbose_name='Картинка загрузки')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
