# Generated by Django 5.0.1 on 2024-02-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCheap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('descriprion', models.TextField(verbose_name='Описание продукта')),
                ('new_price', models.SmallIntegerField(verbose_name='Цена продукта со скидкой')),
                ('old_price', models.SmallIntegerField(verbose_name='Цена продукта без скидки')),
            ],
            options={
                'verbose_name': 'Продукт по скидке',
                'verbose_name_plural': 'Продукты по скидкам',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта')),
                ('photo', models.ImageField(upload_to='shop_products/', verbose_name='Фото продукта')),
                ('new_price', models.SmallIntegerField(verbose_name='Цена продукта со скидкой')),
                ('old_price', models.SmallIntegerField(verbose_name='Цена продукта без скидки')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='description_bottom',
            field=models.TextField(default=1, verbose_name='Описание снизу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='logo_bottom',
            field=models.ImageField(default=1, upload_to='settings/bottom_logo/', verbose_name='Логотип снизу'),
            preserve_default=False,
        ),
    ]
