# Generated by Django 5.0.1 on 2024-02-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_shopcheap_shopproduct_settings_description_bottom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcheap',
            old_name='descriprion',
            new_name='descriprtion',
        ),
    ]
