# Generated by Django 5.0.1 on 2024-02-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_descriprtion_shopcheap_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCheap',
        ),
        migrations.DeleteModel(
            name='ShopProduct',
        ),
    ]
