# Generated by Django 5.0.1 on 2024-02-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_shopcheap_delete_shopproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='galery/', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название картинки')),
            ],
            options={
                'verbose_name': 'Фото в галереи',
                'verbose_name_plural': 'Фото в галерее',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на инстаграм'),
        ),
        migrations.AddField(
            model_name='settings',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на телеграм'),
        ),
        migrations.AddField(
            model_name='settings',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на ютуб'),
        ),
    ]
