# Generated by Django 5.0.1 on 2024-02-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_galery_settings_instagram_settings_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='link',
            field=models.URLField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
