# Generated by Django 5.0.1 on 2024-02-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_contact_options_contact_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок ошибки')),
                ('description', models.TextField(verbose_name='Текст ошибки')),
                ('image', models.ImageField(upload_to='error/', verbose_name='Картинка ошибки')),
            ],
            options={
                'verbose_name': 'Настройка ошибки 404',
                'verbose_name_plural': 'Настройки ошибок 404',
            },
        ),
    ]
