# Generated by Django 5.0.1 on 2024-02-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename__copyright_settings_copyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='coming/', verbose_name='Картинка')),
                ('date', models.DateTimeField(verbose_name='Конец отсчета')),
            ],
            options={
                'verbose_name': 'Настройка страницы coming soon',
                'verbose_name_plural': 'Настройки страниц coming soon',
            },
        ),
    ]
