# Generated by Django 5.0.1 on 2024-02-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_coming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coming',
            name='date',
        ),
    ]
