# Generated by Django 5.0.1 on 2024-02-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_title', models.CharField(max_length=150, verbose_name='Верхний заголовок')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('old_price', models.SmallIntegerField(verbose_name='Старая цена')),
                ('new_price', models.SmallIntegerField(verbose_name='Новая цена')),
                ('title_banner', models.CharField(max_length=255, verbose_name='Заголовок баннера')),
                ('desc_banner', models.TextField(verbose_name='Описание баннера')),
                ('image_banner', models.ImageField(upload_to='settings2/', verbose_name='Картинка баннера')),
                ('video', models.URLField(verbose_name='Ссылка на видео "как зарегестрироваться"')),
            ],
            options={
                'verbose_name': 'Настройка второй главной страницы',
                'verbose_name_plural': 'Настройки второй главной страницы',
            },
        ),
    ]
