# Generated by Django 5.0.1 on 2024-02-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_settingsthree'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=255, verbose_name='Заголовок 1')),
                ('desc_1', models.TextField(verbose_name='Описание 1')),
                ('banner_1', models.ImageField(upload_to='settings4/banner1/', verbose_name='Баннер 1')),
                ('title_2', models.CharField(max_length=255, verbose_name='Заголовок 2')),
                ('banner_2', models.ImageField(upload_to='settings4/banner2/', verbose_name='Баннер 2')),
            ],
            options={
                'verbose_name': 'Настройка четвертой главной страницы',
                'verbose_name_plural': 'Настройки четвертой главной страницы',
            },
        ),
    ]
