# Generated by Django 5.0.1 on 2024-02-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_settingsfour'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=255, verbose_name='Заголовок 1')),
                ('image_1', models.ImageField(upload_to='settings5/banner1/', verbose_name='Баннер 1')),
                ('minititle', models.CharField(max_length=50, verbose_name='Мини заголовок 1')),
                ('new_price', models.SmallIntegerField(verbose_name='Новая цена')),
                ('old_price', models.SmallIntegerField(verbose_name='Старая цена')),
                ('title_2', models.CharField(max_length=255, verbose_name='Заголовок 2')),
                ('desc_2', models.TextField(verbose_name='Описание 2')),
                ('image_2', models.ImageField(upload_to='settings5/banner2/', verbose_name='Баннер 2')),
            ],
            options={
                'verbose_name': 'Настройка пятой главной страницы',
                'verbose_name_plural': 'Настройки пятой главной страницы',
            },
        ),
    ]
