# Generated by Django 5.0.1 on 2024-02-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_settingsfive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('person', models.SmallIntegerField(verbose_name='Количество человек')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время бронирования')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
